version: "3.8"

services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: brunoosilva/tasks-api
    container_name: task-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://user:password@mysql:3306/task_management
      - JWT_SECRET=seu_jwt_secret_seguro
    networks:
      - task-network

  mysql:
    image: mysql:8.0
    container_name: task-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=task_management
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - task-network
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    container_name: task-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
